server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # This will help to insert the data.sql data if tables are empty, though it will run everytime but data.sql script wil insert 
  # only if data is not present.
  sql:
    init:
      mode: always
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true 
    # forces Spring Boot to follow this order:
    # 1. Hibernate scans your User and Role entities.
    # 2. Hibernate creates the users, roles, and user_roles tables in MySQL.
    # 3. Then Spring Boot runs data.sql and inserts the data.
  

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret: 50caab1114b4d2550f2713a933d9c58e2348f88e426a9e0cf8e954924b64f862
  expiration: 180000 # 3 mins
  refresh-expiration: 86400000 # 1 day (Refresh Token)